validate phone number
AchieveNL/cabby-app pull request #61
Opened 2024-06-18 23:21 UTC by baali-boudjemaa

2024-06-19 13:34 UTC, OsamaBentaib requested changes
Please check the comments

2024-06-19 13:34 UTC, OsamaBentaib commented on android/app/build.gradle
Why is this change necessary?

2024-06-19 13:34 UTC, OsamaBentaib commented on pubspec.yaml
Why did you add the space here?

2024-06-19 13:34 UTC, OsamaBentaib commented on devtools_options.yaml
What is this for?

2024-06-20 10:54 UTC, baali-boudjemaa commented on pubspec.yaml
i  added it accidentally

2024-06-20 21:31 UTC, OsamaBentaib commented on devtools_options.yaml
You didn't resolve this why??

2024-06-20 21:33 UTC, OsamaBentaib commented
Please fix all the comments i asked for because I see no changes

2024-06-20 22:03 UTC, baaliboudjemaa commented
> Please fix all the comments i asked for because I see no changes

fixed

2024-06-20 22:16 UTC, baali-boudjemaa commented on android/app/build.gradle
There was a conflict in libc++_shared.so module

2024-06-20 22:20 UTC, baali-boudjemaa commented on devtools_options.yaml
i delete it

2024-06-21 14:03 UTC, merged